import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ArrowUpRight, CheckCircle2, Phone, Plane } from "lucide-react";
import { BOOKING_URL, PHONE_DISPLAY, PHONE_HREF, ROUTES, SITE_URL } from "../../site-data";
import MobileMenu from "../../mobile-menu";

export function generateStaticParams(){ return ROUTES.map(r=>({slug:r.slug})); }

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const {slug}=await params; const r=ROUTES.find(x=>x.slug===slug); if(!r)return{};
  return { title:{absolute:r.title}, description:r.copy, alternates:{canonical:`/routes/${slug}`}, openGraph:{title:r.title,description:r.copy,url:`${SITE_URL}/routes/${slug}`,images:[{url:"/john-wayne-airport-master.jpg",alt:"John Wayne Airport"}]},twitter:{card:"summary_large_image",title:r.title,description:r.copy,images:["/john-wayne-airport-master.jpg"]} };
}

const ROUTE_DETAILS:Record<string,{heading:string;copy:string;returnCopy:string}> = {
  "anaheim": {
    "heading": "SNA to Disneyland-area hotels and Anaheim conventions",
    "copy": "For a Disneyland trip, reserve your SNA airport transfer to the exact Anaheim hotel or drop-off address. Include the hotel name and street address rather than only the theme park name. Your hotel entrance may be the best meeting point for a return trip. Convention schedules, luggage and the number of children traveling should be included in the reservation.",
    "returnCopy": "For Anaheim to John Wayne Airport departures, provide your flight departure time and airline. Request a pickup recommendation that accounts for hotel loading, the drive and your airline’s check-in guidance. Confirm child-seat requests and vehicle availability before travel."
  },
  "irvine": {
    "heading": "John Wayne Airport transfers for Irvine business and family travel",
    "copy": "For Irvine offices and corporate campuses, include the building name, suite or visitor entrance and the lead passenger’s mobile number. For UC Irvine or a hotel, supply the exact destination address. These details help distinguish nearby entrances and plan a direct pickup.",
    "returnCopy": "For Irvine to SNA departures, share the flight time, passenger count and luggage details. If your itinerary includes a meeting before the airport, list it as an additional stop when requesting the quote. Confirm the pickup time against your airline’s check-in guidance."
  },
  "dana-point": {
    "heading": "SNA to Dana Point resorts, homes and the harbor",
    "copy": "Dana Point trips can involve a resort entrance, a harbor meeting point or a private residence. Provide the full address and any guest or gate instructions. If a wedding party or family is arriving on separate flights, include each flight and decide whether you need separate transfers.",
    "returnCopy": "For Dana Point to John Wayne Airport departures, allow for the drive north and your airline’s check-in guidance. Share your flight time when requesting a pickup recommendation. Include luggage, golf bags, child-seat requests and planned stops so the vehicle and quote fit the trip."
  },
  "newport-beach": {
    "heading": "SNA transfers to Newport Beach, Newport Coast and Balboa",
    "copy": "Newport Beach airport trips can end at a coastal resort, a Balboa Peninsula rental, a Newport Coast residence or an office near Fashion Island. Give the full street address and the correct guest entrance when booking. A hotel name alone may not identify the driveway where your party should meet the chauffeur. For a vacation rental, include access instructions and a passenger mobile number that will work after landing.",
    "returnCopy": "For Newport Beach to SNA departures, arrange pickup from your actual hotel or residence rather than using a general city meeting point. Tell us about beach equipment, golf bags and large suitcases before selecting the vehicle. If your day includes a stop at an office or another hotel, add that stop to the quote request so the pickup plan accounts for it."
  },
  "laguna-beach": {
    "heading": "Airport transportation for Laguna Beach coastal stays",
    "copy": "A Laguna Beach arrival may involve a downtown hotel, a coastal resort or a hillside vacation home. Include the entrance address and any access restrictions when reserving. For a wedding, separate your airport transfer from the event shuttle schedule: guests arriving on different flights may need different pickup times. Share the number of passengers and bags for each arrival.",
    "returnCopy": "For Laguna Beach to John Wayne Airport departures, provide your airline, flight time and exact pickup address. Coastal traffic and loading at a hotel or hillside residence can affect the schedule. Request a pickup recommendation for your itinerary and confirm it against the airline’s check-in requirements. Any intermediate stop should be arranged before the trip."
  },
  "san-clemente": {
    "heading": "SNA transfers for San Clemente homes and coastal visits",
    "copy": "San Clemente travelers should identify the exact pickup or destination address, whether near the pier, downtown, Talega or another residential neighborhood. For beach trips, list surfboards and other oversized items before choosing a vehicle; passenger capacity alone does not establish luggage capacity. A group arriving on separate flights should provide each flight number and decide whether to travel together or reserve separate transfers.",
    "returnCopy": "For San Clemente to SNA departures, reserve around the flight’s departure time rather than choosing a pickup time based only on the drive. Your schedule also needs room for loading, traffic and airline check-in. Include gate instructions for residential pickups and request any additional stop in advance. Confirm the total quote and waiting terms before booking."
  },
  "orange": {
    "heading": "John Wayne Airport transfers to the City of Orange",
    "copy": "When booking transportation to Orange, provide a full street address so your reservation identifies the City of Orange rather than the wider Orange County area. Trips to Old Towne, Chapman University, a hotel or a medical appointment can require different drop-off entrances. For campus visits, include the building or visitor meeting point and a contact number. Tell us if an appointment requires a specific arrival time.",
    "returnCopy": "For Orange to John Wayne Airport departures, provide the flight number, departure time and pickup entrance. If several passengers are meeting at different addresses, request a multi-stop itinerary when booking. For a medical appointment, discuss any mobility or vehicle requirements with reservations before confirming; a standard airport transfer should not be assumed to include medical transport assistance."
  },
  "avalon": {
    "heading": "SNA to a mainland ferry terminal for Avalon",
    "copy": "Avalon is on Catalina Island. Your ground transfer covers the mainland journey from John Wayne Airport to the ferry terminal you have booked; the ferry crossing is a separate part of the trip. Share the ferry operator, departure port, sailing time and check-in requirement before reserving the car. Do not use your Avalon hotel address as the mainland drop-off location.",
    "returnCopy": "For the return journey, reserve pickup at the mainland ferry terminal where your boat arrives, then continue by car to SNA. Allow for ferry check-in, the crossing, baggage collection and possible schedule changes when planning flights. Ferry tickets and island transportation are separate arrangements; confirm current sailings directly with the operator."
  }
};

function Brand(){return <Link href="/" className="brand premiumBrand"><span className="jwMark">JW<Plane size={15}/></span><strong>JOHN WAYNE<small>AIRPORT LIMOUSINE</small></strong></Link>}

export default async function RoutePage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const r=ROUTES.find(x=>x.slug===slug); if(!r)notFound();
  const detail=ROUTE_DETAILS[slug];
  const neighbors:Record<string,string[]>={"anaheim":["orange","buena-park","garden-grove","irvine"],"irvine":["newport-beach","tustin","costa-mesa","orange"],"newport-beach":["costa-mesa","irvine","laguna-beach","dana-point"],"laguna-beach":["newport-beach","dana-point","laguna-niguel"],"dana-point":["san-clemente","laguna-beach","san-juan-capistrano"],"san-clemente":["dana-point","san-juan-capistrano","mission-viejo"],"orange":["anaheim","tustin","irvine"],"avalon":["dana-point","long-beach","newport-beach"]};
  const related=(neighbors[slug] || ROUTES.filter(x=>x.slug!==slug && x.county===r.county).map(x=>x.slug).slice(0,6)).map(key=>ROUTES.find(x=>x.slug===key)!).filter(Boolean);
  const schema={"@context":"https://schema.org","@type":"Service",name:r.title,url:`${SITE_URL}/routes/${slug}`,areaServed:[r.city,r.county],serviceType:"John Wayne Airport private car and limousine service",provider:{"@type":"LocalBusiness",name:"John Wayne Airport Limousine",telephone:"+1-949-680-5466"}};
  return <>
    <header className="topbar"><div className="shell nav"><Brand/><nav><Link href="/">Airport Service</Link><Link href="/private-aviation">Private Aviation</Link><Link href="/fleet">Fleet</Link><Link href="/service-areas">All Cities</Link><Link href="/#why">Why Us</Link></nav><div className="headerActions"><MobileMenu/><a className="phone" href={PHONE_HREF}><Phone size={18}/>{PHONE_DISPLAY}</a></div></div></header>
    <main>
      <section className="routeHero"><div className="shell"><nav aria-label="Breadcrumb" className="back"><Link href="/">Home</Link> / <Link href="/service-areas">Service areas</Link> / <span>{r.city}</span></nav><p className="kicker">SNA AIRPORT TRANSPORTATION · {r.county.toUpperCase()}</p><h1>{r.title}</h1><p className="lead">{r.copy}</p><div className="actions"><a className="btn primary" href={BOOKING_URL} target="_blank" rel="noreferrer">Reserve this route <ArrowUpRight size={18}/></a><a className="btn dark" href={PHONE_HREF}><Phone size={18}/>{PHONE_DISPLAY}</a></div></div></section>
      <section className="routeBody shell"><div><p className="eyebrow">Private airport transfer</p><h2>SNA to {r.city}, planned around your trip.</h2><p>{slug==="avalon" ? "Reserve a private transfer from John Wayne Airport to your selected mainland ferry terminal for onward travel to Avalon." : `Reserve direct transportation between John Wayne Airport and ${r.city} with a professional chauffeur and a vehicle selected for your passengers and luggage.`} Arrival service can be coordinated using current flight information, while departing travelers can plan pickup around the time they want to reach the terminal.</p><p>For travelers in {r.county}, this service provides a private alternative to shared shuttles and on-demand rides, with one-way, round-trip and multi-stop reservations available.</p>{detail && <><h2>{detail.heading}</h2><p>{detail.copy}</p><h2>{slug==="avalon" ? "Returning from Catalina Island to SNA" : `${r.city} to John Wayne Airport`}</h2><p>{detail.returnCopy}</p><p>Review the <Link href="/fleet">airport vehicle options</Link> and include all passengers, bags and requested stops when requesting a quote. Confirm the total, waiting terms and any special arrangements before booking.</p></>}<ul><li><CheckCircle2/>{slug==="avalon" ? "Mainland airport-to-ferry transportation" : "Private door-to-door transportation"}</li><li><CheckCircle2/>Terminal A, B and C service</li><li><CheckCircle2/>Sedan, SUV and Sprinter options</li><li><CheckCircle2/>Flight-aware arrival coordination</li></ul></div><aside><b>Need help planning?</b><p>Call for airport pickups, group transportation, meet-and-greet requests or multi-stop itineraries.</p><a href={PHONE_HREF}>{PHONE_DISPLAY}</a></aside></section>
      {slug==="anaheim" && <section className="shell serviceRelated"><h2>Private SNA transfers for Disneyland visits</h2><p>For a Disneyland-area stay, name the exact hotel and its passenger entrance when booking. Tell reservations about strollers, child-seat requests and all suitcases before choosing a vehicle. A hotel transfer and a theme-park drop-off may use different locations; confirm the address you want for each journey.</p><h3>Hotel arrivals and return flights</h3><p>If your flight arrives before hotel check-in, coordinate luggage storage directly with the hotel. For the return trip, reserve pickup from the hotel or another agreed location and provide your departure flight. A park closing time should not be used as the only basis for planning an airport departure.</p><h3>Anaheim convention travel</h3><p>For convention arrivals, include the hotel address, meeting time and any additional passengers collected along the way. Separate airport transfers from transportation between hotels and event venues so the quote reflects each requested journey.</p><p><Link href="/sna-airport-pickup">Read the SNA private pickup guide</Link> or review <Link href="/fleet">vehicles and luggage planning</Link>.</p></section>}
      {detail && <section className="shell" style={{paddingBottom:40,maxWidth:1000}}><h2>Planning your {r.city} airport transfer</h2><h3>Where will I meet the chauffeur at SNA?</h3><p>Confirm the meeting location in your reservation and contact your chauffeur after landing and collecting checked bags. Share your airline, flight number and a working mobile number. Meet-and-greet service and special assistance must be arranged in advance. The <a href="https://www.ocair.com/travelers/parking-transport/transportation/">airport transportation guide</a> provides general information; follow your confirmed pickup instructions for your reserved service.</p><h3>What should I include when requesting a quote?</h3><p>Include your travel date, flight details, complete destination address, passenger count, luggage and requested stops. Ask reservations to confirm the full price, waiting charges, cancellation terms and any child-seat request before paying. Pricing depends on the itinerary and vehicle; a request is subject to availability and confirmation.</p><h3>{slug==="avalon" ? "Does the car booking include the ferry?" : `Can I book the return trip from ${r.city}?`}</h3><p>{slug==="avalon" ? "The car reservation covers the mainland transfer. Book the ferry separately and confirm its port and sailing time before arranging the airport ride." : "Request both journeys together, including the return flight and pickup address. Confirm each pickup time and tell reservations about any differences in passengers, luggage or stops on the return trip."}</p></section>}
      <section className="shell serviceInlineLinks"><Link href="/sna-airport-pickup">SNA airport pickup guide</Link><Link href="/private-aviation">SNA private aviation transportation</Link></section><section className="related shell"><p className="eyebrow">More {r.county} routes</p><div className="routeGrid">{related.map(x=><Link href={`/routes/${x.slug}`} className="routeCard" key={x.slug}><span>SNA →</span><h3>{x.city}</h3><b>View route <ArrowRight size={15}/></b></Link>)}</div></section>
    </main>
    <footer><div className="shell credits">John Wayne Airport Limousine · Private SNA transportation to {r.city} · {PHONE_DISPLAY}</div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE_URL},{"@type":"ListItem",position:2,name:"Service areas",item:`${SITE_URL}/service-areas`},{"@type":"ListItem",position:3,name:r.city,item:`${SITE_URL}/routes/${slug}`}]})}}/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  </>;
}
