import type { Metadata } from "next";
import Link from "next/link";
import { Plane, Phone } from "lucide-react";
import MobileMenu from "./mobile-menu";
import { BOOKING_URL, PHONE_DISPLAY, PHONE_HREF, EMAIL, SITE_URL, ROUTES } from "./site-data";
import { SERVICE_ARTICLES, type ServiceArticle } from "./service-content";

export function articleMetadata(a:ServiceArticle):Metadata {
  return {title:{absolute:a.title},description:a.description,alternates:{canonical:a.path},openGraph:{type:"website",title:a.title,description:a.description,url:SITE_URL+a.path,images:[{url:"/john-wayne-airport-master.jpg",alt:"John Wayne Airport"}]},twitter:{card:"summary_large_image",title:a.title,description:a.description,images:["/john-wayne-airport-master.jpg"]}};
}
function label(path:string){return SERVICE_ARTICLES.find(a=>a.path===path)?.label || ROUTES.find(r=>`/routes/${r.slug}`===path)?.city || (path==="/fleet" ? "Luxury Fleet" : "Service Areas");}
export default function ServiceArticlePage({article:a}:{article:ServiceArticle}){
 const privateChild=a.path.startsWith("/private-aviation/");
 const crumbs=[{name:"Home",item:SITE_URL},...(privateChild?[{name:"Private Aviation",item:SITE_URL+"/private-aviation"}]:[]),{name:a.label,item:SITE_URL+a.path}];
 const schema={"@context":"https://schema.org","@graph":[{"@type":"Service",name:a.title,description:a.description,url:SITE_URL+a.path,serviceType:"Private chauffeur transportation",areaServed:"Orange County, California",provider:{"@type":"LocalBusiness",name:"John Wayne Airport Limousine",url:SITE_URL,telephone:PHONE_HREF.replace("tel:","")}}, {"@type":"BreadcrumbList",itemListElement:crumbs.map((c,i)=>({"@type":"ListItem",position:i+1,...c}))}]};
 return <><header className="topbar"><div className="shell nav"><Link href="/" className="brand premiumBrand"><span className="jwMark">JW<Plane size={15}/></span><strong>JOHN WAYNE<small>AIRPORT LIMOUSINE</small></strong></Link><nav><Link href="/#service">Airport Service</Link><Link href="/private-aviation">Private Aviation</Link><Link href="/fleet">Fleet</Link><Link href="/service-areas">All Cities</Link><Link href="/#why">Why Us</Link></nav><div className="headerActions"><MobileMenu/><a className="phone" href={PHONE_HREF}><Phone size={18}/>{PHONE_DISPLAY}</a></div></div></header>
 <main className="serviceArticle"><div className="serviceBanner"><img src="/john-wayne-airport-master.jpg" alt="John Wayne Airport" width="1536" height="1024"/></div><section className="serviceHeading"><div className="shell"><nav aria-label="Breadcrumb" className="serviceCrumbs">{crumbs.map((c,i)=><span key={c.item}>{i>0 && " / "}{i===crumbs.length-1?<span aria-current="page">{c.name}</span>:<Link href={c.item}>{c.name}</Link>}</span>)}</nav><p className="eyebrow light">John Wayne Airport · SNA</p><h1>{a.title}</h1><p>{a.description}</p><div className="actions"><a className="btn primary" href={BOOKING_URL} target="_blank" rel="noreferrer">Request a quote</a><a className="btn glass" href={PHONE_HREF}>{PHONE_DISPLAY}</a></div></div></section>
 <div className="shell serviceLayout"><article>{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}{a.source && <p className="serviceSource">Facility and visitor reference: <a href={a.source}>official location information</a>. Confirm current access instructions before travel.</p>}</article><aside><h2>Reserve your ground transfer</h2><p>Send your date, flight or tail number, pickup facility, destination, passengers and luggage.</p><a className="btn primary" href={BOOKING_URL} target="_blank" rel="noreferrer">Plan your ride</a><p><a href={PHONE_HREF}>{PHONE_DISPLAY}</a></p><p>Vehicle availability, waiting terms and special requests are confirmed with your reservation.</p></aside></div>
 <section className="shell serviceRelated"><h2>{a.path==="/private-aviation" ? "Select your SNA facility" : "Plan the rest of your trip"}</h2><div className="routeGrid">{a.links.map(path=><Link className="routeCard" href={path} key={path}><span>SNA TRANSPORTATION</span><h3>{label(path)}</h3><b>View details →</b></Link>)}</div></section></main>
 <footer><div className="shell footerGrid"><div><b>John Wayne Airport Limousine</b><p>Prearranged private car and executive SUV transportation.</p><a href={PHONE_HREF}>{PHONE_DISPLAY}</a><a href={`mailto:${EMAIL}`}>{EMAIL}</a></div><div><b>Reservations</b><span>Monday–Sunday<br/>6:00 AM–10:00 PM</span><span>Visa, Mastercard, American Express, Venmo &amp; Zelle</span><a href={BOOKING_URL} target="_blank" rel="noreferrer">Book online</a></div><div><b>Explore</b><Link href="/private-aviation">Private Aviation</Link><Link href="/sna-airport-pickup">SNA Pickup Guide</Link><Link href="/fleet">Luxury Fleet</Link><Link href="/service-areas">Service Areas</Link></div></div></footer>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/></>;
}
